name: JetStream
options:
  bundleIdPrefix: com.iamsohail
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

schemes:
  JetStream:
    build:
      targets:
        JetStream: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - JetStreamTests
    profile:
      config: Release
    archive:
      config: Release

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "12.9.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    exactVersion: "7.1.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: "JetStream"

targets:
  JetStream:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: JetStream
        excludes:
          - "**/.DS_Store"
    capabilities:
      Push Notifications: {}
      Background Modes:
        modes:
          - remote-notification
      Sign in with Apple: {}
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: GoogleSignIn
        product: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iamsohail.JetStream
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: Z2Z347GW4T
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    info:
      path: JetStream/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIBackgroundModes:
          - remote-notification
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - com.googleusercontent.apps.732472215581-c07mel2qg2g71qcarus9da8buki8toeq
            CFBundleURLName: Google Sign-In
          - CFBundleURLSchemes:
              - jetstream
            CFBundleURLName: JetStream Deep Links
    entitlements:
      path: JetStream/JetStream.entitlements
      properties:
        aps-environment: production
        com.apple.developer.applesignin:
          - Default

  JetStreamTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: JetStreamTests
    dependencies:
      - target: JetStream
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iamsohail.JetStreamTests

  JetStreamUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: JetStreamUITests
    dependencies:
      - target: JetStream
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iamsohail.JetStreamUITests
